//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OlindaSharksWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OlindaSharksDBEntities : DbContext
    {
        public OlindaSharksDBEntities()
            : base("name=OlindaSharksDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Month> Month { get; set; }
        public virtual DbSet<MonthlyPayment> MonthlyPayment { get; set; }
        public virtual DbSet<MonthYear> MonthYear { get; set; }
        public virtual DbSet<Payment> Payment { get; set; }
        public virtual DbSet<Player> Player { get; set; }
        public virtual DbSet<SystemUser> SystemUser { get; set; }
        public virtual DbSet<Team> Team { get; set; }
        public virtual DbSet<Year> Year { get; set; }
    }
}
