//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OlindaSharksWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthYear
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MonthYear()
        {
            this.Payment = new HashSet<Payment>();
        }
    
        public int IdMonthYear { get; set; }
        public int IdMonthFk { get; set; }
        public int IdYearFk { get; set; }
    
        public virtual Month Month { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payment { get; set; }
        public virtual Year Year { get; set; }
    }
}
