//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OlindaSharksWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int IdPayment { get; set; }
        public int IdPlayerFk { get; set; }
        public int IdMonthYearFk { get; set; }
        public int IdMonthlyPaymentFk { get; set; }
        public System.DateTime PayDay { get; set; }
    
        public virtual MonthlyPayment MonthlyPayment { get; set; }
        public virtual MonthYear MonthYear { get; set; }
        public virtual Player Player { get; set; }
    }
}
