//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OlindaSharksWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Player()
        {
            this.Payment = new HashSet<Payment>();
        }
    
        public int IdPlayer { get; set; }
        public string Name { get; set; }
        public string Nickname { get; set; }
        public string Cpf { get; set; }
        public string Rg { get; set; }
        public string DateOfBorn { get; set; }
        public string Address { get; set; }
        public string Telephone { get; set; }
        public string ProfileFacebook { get; set; }
        public string ProfileInstagram { get; set; }
        public string Height { get; set; }
        public string Weight { get; set; }
        public int IdTeamFK { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payment { get; set; }
        public virtual Team Team { get; set; }
    }
}
